version: '3.7'

services: 
  react_demo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
      PACKAGE_UPDATE: "true"
      NODE_ENV: dev
    stdin_open: true